version: ~> 1.0

env:
  global:
    - secure: "XtUZPwPRT/XSynlIxdnFUpSPTuA82YGltQOKYdIUGSGOBA6czzJj0/lk9teemfDk4+6Nai99GFIPMaCKZY3uxPt9+wJqt+BX3YijBduq35xf9Ld+Z875xWZkFm/C3eodJJsaZQ2B1F3eRUVOoC8sbyNaPI5FgX59uwlr+1HBD/249Zj6eTo78TYNy6fx/yXlpuifOozYr1siJ00eunHpT061zwvscXKHEDg7Fjkezyi6oA2KO9eUjDH8sFYFx8RB4H8jkJsShHBIYB/pWLbuznPvGhs9opM0Q1+1vdoHD3F3dYAyNMXg0tgacnU59153oct5la6JUEfe7RSD5DQctrELNUGAoS1o/X1M6xgEmwNRM2VUv6fZFziJGVd2viZ+2VnDS4mfMxgBeh3oq0LRLSYTLMCcitdjI1mBuRymaWP2MbIs2XEqMFRJrAufWOUJ2gey922+emKm2a57lPohfUpfbVKaVsmDy6tPY7t2Xuq7frrOpLrL9H6TV1EqZTp+zBSg+dM38OsVDQ1J1GZa53ESc4YvG941jSjbAgo0Ji1xIcx9eAOGrYiymYUlr3Z2HOoOqGn0dSAJaGqfrSLP/F/kPlj5FzFm8IcsN+UyvQEf0quT2BjJK7/75zNj6goN2UbpZ4BynTBIXr5yIFnyq6hKfUBs+XZoGVxkvO0VL2o="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="docs-requirements.txt dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdsdevices"

    # The name of the conda package
    - CONDA_PACKAGE="pcdsdevices"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
