{% set data = load_setup_py_data() %}

package:
  name: pcds-devices
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - python {{PY_VER}}*,>=3
    - setuptools

  run:
    - python {{PY_VER}}*,>=3
    - ophyd ==0.6.1
    - happi

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/slaclab/pcds-devices
  license: SLAC Open License
  summary: IOC definitions for LCLS Beamline Devices
