{% set data = load_setup_py_data() %}

package:
  name: pcdsdevices
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - ophyd >=1.5.1
    - bluesky >=1.6.4
    - pyepics >=3.4.2
    - pytmc >=2.7.0
    - pyyaml
    - pint
    - scipy
    - matplotlib <3
    - periodictable
    - happi
    - schema
    - pcdsutils
    - pcdscalc

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  license: SLAC Open License
  summary: IOC definitions for LCLS Beamline Devices
