{% set data = load_setup_py_data() %}

package:
  name: pcdsdevices
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - ophyd 1.4.0rc4|>=1.4.0
    - bluesky >=1.2.0
    - pyepics >=3.4.1
    - pyyaml
    - cf_units >=2.0.1
    - scipy
    - matplotlib <3

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  license: SLAC Open License
  summary: IOC definitions for LCLS Beamline Devices
